"""
one_shot_cgh.py

Non-iterative ("one-shot") phase-only CGH generation, meant to be attached
to the existing CGHGenerator class as a fast alternative to the ADAM /
ADAMwGS iterative optimizers.

Instead of optimizing phase over `numIter` gradient steps with an annealed
Gumbel-softmax quantizer, this computes the hologram analytically:

    1. Build the target complex field: sqrt(intensity) * exp(i * hash_phase)
       -- `hash_phase` is a deterministic per-pixel phase mask generated by
       hashing pixel coordinates (a reproducible stand-in for the random
       phase diffuser used in single-pass Gerchberg-Saxton).
    2. Propagate ONCE through the same Fourier physics (`self.prop`) that
       the iterative methods use every step.
    3. Snap every pixel's continuous phase to the nearest physically
       available mirror state (the 16-entry pLevel table) in one
       vectorized lookup -- this is the "hash table" step, replacing the
       per-pixel Python loop in the original `quantiz`/`discretePhase`.
    4. Optionally run one pass of Floyd-Steinberg error diffusion so
       quantization error is spread spatially, similar in spirit to what
       the annealed soft-quantizer does over many iterations, but computed
       once.

Trade-off vs. ADAM / ADAMwGS: this will run in a fraction of the time
(one FFT + one vectorized lookup vs. numIter optimizer steps), but will
generally show lower diffraction efficiency / more non-uniformity, since
there's no feedback loop correcting for the quantization error globally.
If you need one-shot speed AND ADAM-level quality, the right move is to
amortize the optimization into a trained network (train once offline using
the same physics as the loss; inference is then a single forward pass).
Happy to help build that version too if this doesn't get you close enough.

Usage:
    from one_shot_cgh import attach_one_shot
    attach_one_shot(CGHGenerator)   # monkeypatches the methods below in

    gen = CGHGenerator()
    gen.createCGH_OneShot(deviceDict, filename="target.png", dither=True)
    # gen.CGH_mapped / gen.CGH_phase are now populated, same as createCGH()
"""

import numpy as np


def _hash_phase_diffuser(shape, seed=0):
    """
    Deterministic per-pixel phase mask generated by hashing pixel
    coordinates (xorshift-style 32-bit integer hash). Plays the role a
    random phase seed plays in single-pass Gerchberg-Saxton -- spreads
    target energy across the aperture -- but is reproducible and cheap
    to regenerate/cache per (height, width, seed).
    """
    h, w = shape
    yy, xx = np.meshgrid(np.arange(h, dtype=np.uint32),
                          np.arange(w, dtype=np.uint32), indexing="ij")
    key = (xx * np.uint32(73856093)) ^ (yy * np.uint32(19349663)) ^ np.uint32(seed * 83492791 + 1)
    key ^= key >> np.uint32(13)
    key = key * np.uint32(2654435761)
    key ^= key >> np.uint32(16)
    frac = key.astype(np.float64) / np.float64(2 ** 32)
    return 2 * np.pi * frac


def _nearest_quantize(phase_frac, codebook, nLevel):
    """
    Vectorized nearest-level lookup: every pixel's continuous phase
    (as a 0..1 fraction) is snapped to the closest of the `nLevel`
    physically available mirror states in one shot -- no per-pixel
    Python loop, no iterative annealing.
    """
    val = np.mod(phase_frac, 1.0)
    idx = np.searchsorted(codebook, val, side="left")
    idx = np.clip(idx, 1, len(codebook) - 1)
    left = codebook[idx - 1]
    right = codebook[idx]
    idx = idx - (np.abs(val - left) < np.abs(val - right)).astype(int)
    state_map = (idx % nLevel).astype(np.float64)
    phase_disc = codebook[idx].copy()
    phase_disc[phase_disc == 1] = 0.0
    return state_map, phase_disc


def _dither_quantize(phase_frac, codebook, nLevel):
    """
    Floyd-Steinberg error diffusion on top of the nearest-level lookup.
    Still a single deterministic pass over the image (no optimizer, no
    gradients) but spreads quantization error into neighboring pixels,
    which is what the annealed Gumbel-softmax step is doing implicitly
    over many training iterations -- here it happens once.
    """
    h, w = phase_frac.shape
    buf = np.mod(phase_frac, 1.0).copy()
    state_map = np.zeros((h, w), dtype=np.float64)
    phase_disc = np.zeros((h, w), dtype=np.float64)

    for y in range(h):
        x_range = range(w) if (y % 2 == 0) else range(w - 1, -1, -1)
        for x in x_range:
            val = np.mod(buf[y, x], 1.0)
            idx = np.searchsorted(codebook, val, side="left")
            idx = int(np.clip(idx, 1, len(codebook) - 1))
            if abs(val - codebook[idx - 1]) < abs(val - codebook[idx]):
                idx -= 1
            q = codebook[idx]
            state_map[y, x] = idx % nLevel
            phase_disc[y, x] = 0.0 if q == 1 else q

            err = val - q
            nxt = x + 1 if (y % 2 == 0) else x - 1
            if 0 <= nxt < w:
                buf[y, nxt] += err * 7 / 16
            if y + 1 < h:
                if 0 <= x - 1 < w:
                    buf[y + 1, x - 1] += err * 3 / 16
                buf[y + 1, x] += err * 5 / 16
                if 0 <= x + 1 < w:
                    buf[y + 1, x + 1] += err * 1 / 16

    return state_map, phase_disc


def oneShotPhase(self, seed=0):
    """
    Single-shot analytic phase: sqrt(target) * hashed-phase diffuser,
    propagated once through the same Fourier physics used elsewhere
    (self.prop), phase of the result kept as the hologram phase.
    """
    if self.imTarget is None:
        raise ValueError("No target loaded. Call loadTarget()/resizeTarget() first.")

    amplitude = np.sqrt(np.clip(self.imTarget, 0, None))
    diffuser = _hash_phase_diffuser(self.imTarget.shape, seed=seed)
    field_target = amplitude * np.exp(1j * diffuser)

    # Inverse of the forward prop used by recoverImg/reconstruct elsewhere:
    # image-plane field -> hologram-plane field, in one call.
    E_holo = self.prop("backward", field_target, "FOURIER")
    return np.mod(np.angle(E_holo), 2 * np.pi)


def createCGH_OneShot(self, DeviceDictionary, filename="", colorChannel=0,
                       FlipUD=False, FlipLR=False, InvertTarget=False,
                       ShiftFOV=True, binarizeTarget=False, targetThreshold=0.5,
                       preserveAspect=True, seed=0, dither=True):
    """
    Drop-in, non-iterative replacement for createCGH(). Same signature
    style, same populated attributes on exit (CGH_mapped, CGH_phase,
    imRecovered_cont/disc), but ~1 FFT + 1 vectorized quantization pass
    instead of numIter optimizer steps.
    """
    if str(DeviceDictionary["device"]).upper() != "0.67":
        raise ValueError("TIPLMSuite only supports the 0.67 device.")

    self.bitPlanes = 1
    self.loadTarget(filename, colorChannel)
    self.resizeTarget(self.lambda_m, DeviceDictionary["h"], DeviceDictionary["w"],
                       DeviceDictionary["pitchW"], DeviceDictionary["pitchH"],
                       ShiftFOV, preserveAspect)
    self.pitchW = DeviceDictionary["pitchW"]
    self.pitchH = DeviceDictionary["pitchH"]
    if binarizeTarget:
        self.binarizeTarget(targetThreshold)
    self.updateTarget(FlipUD, FlipLR, InvertTarget)

    self.CGH_output_cont = self.oneShotPhase(seed=seed)

    codebook = np.sort(np.asarray(DeviceDictionary["pLevel"]), axis=0)
    nLevel = DeviceDictionary["nLevel"]
    codebook = codebook[:nLevel]
    phase_frac = self.CGH_output_cont / (2 * np.pi)

    if dither:
        state_map, phase_disc_frac = _dither_quantize(phase_frac, codebook, nLevel)
    else:
        state_map, phase_disc_frac = _nearest_quantize(phase_frac, codebook, nLevel)

    self.CGH_output_phase_disc = 2 * np.pi * phase_disc_frac
    self.CGH_output_state_disc = state_map
    self.CGH_output_disc = state_map

    self.recoverImg(ShiftFOV, "FOURIER")
    self.CGH_mapped = self.deviceLibary.formatPLM(DeviceDictionary, state_map)
    self.CGH_phase = self.CGH_output_phase_disc


def attach_one_shot(cls):
    """Monkeypatch the one-shot methods onto an existing CGHGenerator class."""
    cls.oneShotPhase = oneShotPhase
    cls.createCGH_OneShot = createCGH_OneShot
    return cls
